# Generated by Django 4.0.6 on 2022-07-30 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('shape', models.CharField(choices=[('R', 'Rectangle'), ('T', 'Tube'), ('C', 'Cup')], default='R', max_length=1)),
                ('size', models.CharField(max_length=100)),
            ],
        ),
    ]
