# Generated by Django 4.0.6 on 2022-07-20 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('tip_width', models.CharField(max_length=100)),
                ('tip_type', models.CharField(max_length=100)),
                ('number_owned', models.IntegerField()),
            ],
        ),
    ]
