# Generated by Django 4.0.6 on 2022-07-30 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pen_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bin',
            old_name='location',
            new_name='room',
        ),
        migrations.AddField(
            model_name='bin',
            name='shelving_unit',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bin',
            name='shape',
            field=models.CharField(max_length=100),
        ),
    ]
