# Generated by Django 4.0.6 on 2022-07-30 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pen_app', '0002_rename_location_bin_room_bin_shelving_unit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('number_owned', models.IntegerField()),
                ('bin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pen_app.bin')),
            ],
        ),
    ]
