# Generated by Django 4.0.6 on 2022-07-30 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pen_app', '0003_pen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
            ],
        ),
    ]
