# Generated by Django 4.0.6 on 2022-07-30 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pen_app', '0004_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='explaination',
            field=models.TextField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
